#! /bin/bash
#SBATCH -J compare
#SBATCH -o compare.log
#SBATCH --nodes=1 --ntasks-per-node=1 --cpus-per-task=1

module purge
module load cmake Generic-AArch64/RHEL/7/gcc/9.3.0

export OMP_NUM_THREADS=1

#CORE="1 2 4 8 16 32 64 128 192 252"

NBATCH="1 2 4 8 16 32 64 128 192 256 512 1024"
for n in ${NBATCH}; do
  srun --cpu-bind=v,ldoms ./pali_sq_sum  ${n} 1 8192 39 60 2 10
  srun --cpu-bind=v,ldoms ./helib_sq_sum ${n} 8192 39 159 2
  srun --cpu-bind=v,ldoms ./seal_sq_sum ${n} 8192 39
done

